# Site Configuration
title: "Pivotal Token Representations Encode Reasoning Shifts in Large Language Models"
description: "A comprehensive study on how pivotal tokens encode reasoning shifts in large language models through linear probing"
author: ["Steven N., Taiwo Omoya, Zurabi Kochiashivili, Dylan Tran"]
email: ["svngo@ucsd.edu", "kevin@algoverse.us"]
url: "https://debbie1505.github.io"
baseurl: "/Linear-Probe_PTS-Research-Page"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/New_York

# Collections
collections:
  authors:
    output: true
    permalink: /authors/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# SEO
seo:
  type: "AcademicPaper"
  locale: "en_US"

# Social
social:
  name: "Taiwo Omoya"
  links:
    - "https://github.com/debbie1505"

# Paper metadata
paper:
  title: "Pivotal Token Representations Encode Reasoning Shifts in Large Language Models"
  authors: ["Steven N.", "Taiwo Omoya", "Zurabi Kochiashvii", "Dylan Tran"]
  year: 2025
  doi: "TBD"
  abstract: "As large language models (LLMs) continue to scale in reasoning capability, the mechanisms by which their internal representations encode intermediate decision-making steps remain poorly understood. Prior work has utilized Pivotal Token Search (PTS) to identify pivotal tokens—tokens within a reasoning trace that substantially influence the probability of a correct final answer—but none have formulated methods for interpreting them. In this work, we present a probing method to predict and classify pivotal features underlying Qwen3-0.6B activations."
  keywords: ["large language models", "reasoning", "pivotal tokens", "linear probing", "mechanistic interpretability", "neural networks"]
  pdf_url: "https://openreview.net/pdf?id=SAY6fuvpwo"
  openreview_id: "SAY6fuvpwo"
  

# Navigation
navigation:
  - title: "Abstract"
    url: "/abstract"
  - title: "Methodology"
    url: "/methodology"
  - title: "Results"
    url: "/results"
  - title: "Discussion"
    url: "/discussion"
  - title: "References"
    url: "/references"
  - title: "About"
    url: "/about"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
